name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint

    - name: Run pylint
      run: |
          pylint QhX/ --disable=invalid-name,line-too-long
      continue-on-error: true
      env:
        PYLINTHINTS: "Consistent naming conventions such as `snake_case` help maintain readability, reduce conflicts, and ensure compatibility with Python's ecosystem."

    - name: Run tests
      run: |
        python -m pytest -s QhX/tests/
